### ISSUE TITLE
Tutorial Please

### ISSUE THREAD

**Issue by ariona** [markvandenbergh/phonegap-plugin-ios-quick-look#1]
I need a little instruction here, from installing to using this plugin

**Comment by markvandenbergh** [comment]
Here's an old example project I created two years ago. Don't know if it's still compatible with the latest XCode versions but it might help with some code samples.

[QuickLook.zip](https://github.com/markvandenbergh/phonegap-plugin-ios-quick-look/files/120279/QuickLook.zip)
